name: het_snp_kmers
version: "1.0"
author: Haynes Heaton <whheaton@gmail.com>
about: Finds kmer pairs that are different in the middle base and each have roughly haploid coverage. Meant for illumina data as an initial step for de novo phasing.
args:
    - kmer_counts:
        long: kmer_counts
        short: i
        takes_value: true
        required: true
        help: kmer counts in tsv kmer\tcount (kmer is reverse compliment canonicalized)
    - min_coverage:
        long: min_coverage
        takes_value: true
        required: true
        help: min coverage for each kmer of the pair
    - max_coverage:
        long: max_coverage
        takes_value: true
        required: true
        help: max coverage for each kmer of the pair
    - max_error:
        long: max_error
        takes_value: true
        help: max count of the other two kmers with middle base changed. For best results best to be strict and use 0.
    - max_total_coverage:
        long: max_total_coverage
        takes_value: true
        required: false
        help: max sum of all kmers with middle base changed
    - unpaired_het_modimizer:
        long: unpaired_het_modimizer
        takes_value: true
        required: true
        help: use unpaired het kmers which satisfy kmer % modimizer == 0
    - hom_modimizer:
        long: hom_modimizer
        takes_value: true
        required: true
        help: use homozygous kmers which satisfy kmer % modimizer == 0
